/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.cglib.CgClass;
import org.example.classes.Man;
import org.example.classes.Person;
import org.example.classes.PersonInvocationHandler;

import java.lang.reflect.Proxy;


public class App {
    public static void main(String[] args) {
        Man shashank = new Man("Shashank", 20, "Delhi", "India");
        ClassLoader shashankClassLoader = shashank.getClass().getClassLoader();
        Class[] interfaces = shashank.getClass().getInterfaces();
        Person proxyshashank = (Person) Proxy.newProxyInstance(shashankClassLoader, interfaces, new PersonInvocationHandler(shashank));
        proxyshashank.introduce(shashank.getName());
//        CgClass.main(args);
    }
}
